/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/sites': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Sites */
		get: operations['list_sites_sites_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sites/{site}/work-types': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Work Types */
		get: operations['list_work_types_sites__site__work_types_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/works': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Works */
		get: operations['list_works_works_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/works/{site}/{slug}/words': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Work Words
		 * @description Word positions, grouped into lines and then into the script variants a work has.
		 *
		 *     `lang` is the site's own variant id rather than a language code: that is what the source
		 *     supplies, and mapping it would invent a fact the archive does not hold.
		 */
		get: operations['get_work_words_works__site___slug__words_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/works/{site}/{slug}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Work */
		get: operations['get_work_works__site___slug__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/poets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Poets */
		get: operations['list_poets_poets_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/poets/{site}/{slug}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Poet */
		get: operations['get_poet_poets__site___slug__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/poets/{site}/{slug}/works': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Poet Works */
		get: operations['get_poet_works_poets__site___slug__works_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entries': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Entries */
		get: operations['list_entries_entries_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entries/lookup': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Lookup Entry
		 * @description Resolve a word code to its entry and what it means.
		 *
		 *     The senses come back with it because this is the tap-a-word route: the headword's three
		 *     scripts are three spellings of the word the reader is already looking at, so a response
		 *     without definitions answers nothing.
		 *
		 *     Only rekhta's poetry codes resolve, all 262,030 of them. The 592,351 codes carried by
		 *     hindwi and sufinama works match no entry, and neither does the prose recovered from
		 *     rekhta.org's own pages, which encodes the same words differently. Those 404 by design.
		 */
		get: operations['lookup_entry_entries_lookup_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/entries/{site}/{slug}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Entry */
		get: operations['get_entry_entries__site___slug__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/tags': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Tags */
		get: operations['list_tags_tags_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/tags/{tag}/works': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Tag Works */
		get: operations['get_tag_works_tags__tag__works_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Search */
		get: operations['search_search_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health */
		get: operations['health_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** EntityDetail */
		EntityDetail: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Entity Type */
			entity_type: string;
			/** Name */
			name: string | null;
			/** Name Hindi */
			name_hindi: string | null;
			/** Name Urdu */
			name_urdu: string | null;
			/** Name Translit */
			name_translit: string | null;
			/** Born */
			born: string | null;
			/** Died */
			died: string | null;
			/** Description */
			description: string | null;
			/** Works */
			works: number;
		};
		/** EntitySummary */
		EntitySummary: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Entity Type */
			entity_type: string;
			/** Name */
			name: string | null;
			/** Name Hindi */
			name_hindi: string | null;
			/** Name Urdu */
			name_urdu: string | null;
			/** Name Translit */
			name_translit: string | null;
			/** Born */
			born: string | null;
			/** Died */
			died: string | null;
		};
		/** EntryDetail */
		EntryDetail: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Headword */
			headword: string | null;
			/** Headword Hindi */
			headword_hindi: string | null;
			/** Headword Urdu */
			headword_urdu: string | null;
			/** Vazn */
			vazn: string | null;
			/** Trivia */
			trivia: string | null;
			/** Audio Url */
			audio_url: string | null;
			/** Video Url */
			video_url: string | null;
			/** Senses */
			senses: components['schemas']['Sense'][];
			/** Examples */
			examples: string[];
			/** Relations */
			relations: components['schemas']['Relation'][];
			/** Shers */
			shers: components['schemas']['Sher'][];
		};
		/**
		 * EntryGloss
		 * @description What a reader needs when they tap a word: the headword and what it means.
		 *
		 *     A summary alone is useless at the point of use, because the three headword scripts are
		 *     three spellings of the word already on the page. The senses are the answer.
		 */
		EntryGloss: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Headword */
			headword: string | null;
			/** Headword Hindi */
			headword_hindi: string | null;
			/** Headword Urdu */
			headword_urdu: string | null;
			/** Senses */
			senses: components['schemas']['Sense'][];
		};
		/** EntrySummary */
		EntrySummary: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Headword */
			headword: string | null;
			/** Headword Hindi */
			headword_hindi: string | null;
			/** Headword Urdu */
			headword_urdu: string | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** Health */
		Health: {
			/** Status */
			status: string;
			/** Works */
			works: number;
		};
		/** Page[EntitySummary] */
		Page_EntitySummary_: {
			/** Items */
			items: components['schemas']['EntitySummary'][];
			/** Total */
			total: number;
			/** Limit */
			limit: number;
			/** Offset */
			offset: number;
		};
		/** Page[EntrySummary] */
		Page_EntrySummary_: {
			/** Items */
			items: components['schemas']['EntrySummary'][];
			/** Total */
			total: number;
			/** Limit */
			limit: number;
			/** Offset */
			offset: number;
		};
		/** Page[SearchHit] */
		Page_SearchHit_: {
			/** Items */
			items: components['schemas']['SearchHit'][];
			/** Total */
			total: number;
			/** Limit */
			limit: number;
			/** Offset */
			offset: number;
		};
		/** Page[TagSummary] */
		Page_TagSummary_: {
			/** Items */
			items: components['schemas']['TagSummary'][];
			/** Total */
			total: number;
			/** Limit */
			limit: number;
			/** Offset */
			offset: number;
		};
		/** Page[WorkSummary] */
		Page_WorkSummary_: {
			/** Items */
			items: components['schemas']['WorkSummary'][];
			/** Total */
			total: number;
			/** Limit */
			limit: number;
			/** Offset */
			offset: number;
		};
		/** Relation */
		Relation: {
			/** Rel Type */
			rel_type: string;
			/** Target Text */
			target_text: string;
			/** Target Meaning */
			target_meaning: string | null;
		};
		/** SearchHit */
		SearchHit: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Kind */
			kind: string;
			/** Title */
			title: string | null;
			/** Snippet */
			snippet: string;
		};
		/** Sense */
		Sense: {
			/** Lang */
			lang: string;
			/** Pos */
			pos: string | null;
			/** Definition */
			definition: string;
		};
		/** Sher */
		Sher: {
			/** Lines */
			lines: string;
			/** Lines Alt */
			lines_alt: string | null;
			/** Poet */
			poet: string | null;
		};
		/** SiteSummary */
		SiteSummary: {
			/** Site */
			site: string;
			/** Works */
			works: number;
			/** Entries */
			entries: number;
			/** Entities */
			entities: number;
		};
		/** TagSummary */
		TagSummary: {
			/** Tag */
			tag: string;
			/** Works */
			works: number;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/**
		 * Word
		 * @description One word occurrence in reading order.
		 *
		 *     `code` is the source's own token, returned as it was captured. Rekhta's poetry codes
		 *     resolve through `/entries/lookup`; the codes on hindwi and sufinama works, and on the
		 *     prose recovered from rekhta.org's pages, use other encodings and resolve to nothing. A
		 *     client cannot tell which from the code alone, so treat a 404 from lookup as normal.
		 */
		Word: {
			/** Line */
			line: number;
			/** Ord */
			ord: number;
			/** Word */
			word: string;
			/** Code */
			code: string | null;
		};
		/** WorkDetail */
		WorkDetail: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Work Type */
			work_type: string;
			/** Title */
			title: string | null;
			/** Title Translit */
			title_translit: string | null;
			/** Title Hindi */
			title_hindi: string | null;
			/** Title Urdu */
			title_urdu: string | null;
			/** Author Name */
			author_name: string | null;
			/**
			 * Author Slug
			 * @description `entities.slug` of the author, when the poet page was captured
			 */
			author_slug?: string | null;
			/** Body */
			body: string | null;
			/** Body Hindi */
			body_hindi: string | null;
			/** Body Urdu */
			body_urdu: string | null;
			/**
			 * Explanation
			 * @description the site's own prose gloss, kept out of the verse
			 */
			explanation?: string | null;
			/**
			 * Translation
			 * @description the site's English rendering, kept out of the verse
			 */
			translation?: string | null;
			/** Source */
			source: string | null;
			/** Tags */
			tags: string[];
			/**
			 * Has Words
			 * @description whether word-level positions exist, so a reader can offer word lookup
			 */
			has_words: boolean;
		};
		/** WorkSummary */
		WorkSummary: {
			/** Site */
			site: string;
			/** Slug */
			slug: string;
			/** Work Type */
			work_type: string;
			/** Title */
			title: string | null;
			/** Title Translit */
			title_translit: string | null;
			/** Title Hindi */
			title_hindi: string | null;
			/** Title Urdu */
			title_urdu: string | null;
			/** Author Name */
			author_name: string | null;
			/**
			 * Author Slug
			 * @description `entities.slug` of the author, when the poet page was captured
			 */
			author_slug?: string | null;
		};
		/** WorkTypeSummary */
		WorkTypeSummary: {
			/** Work Type */
			work_type: string;
			/** Works */
			works: number;
		};
		/** WorkWords */
		WorkWords: {
			/** Lang */
			lang: string;
			/** Lines */
			lines: components['schemas']['Word'][][];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_sites_sites_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SiteSummary'][];
				};
			};
		};
	};
	list_work_types_sites__site__work_types_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				site: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkTypeSummary'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_works_works_get: {
		parameters: {
			query?: {
				/** @description rekhta, hindwi or sufinama */
				site?: string | null;
				/** @description ghazals, nazms, stories, ... */
				work_type?: string | null;
				/** @description `entities.slug` of the poet */
				author?: string | null;
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_WorkSummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_work_words_works__site___slug__words_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				site: string;
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkWords'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_work_works__site___slug__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				site: string;
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkDetail'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_poets_poets_get: {
		parameters: {
			query?: {
				/** @description rekhta, hindwi or sufinama */
				site?: string | null;
				/** @description poets, authors, translators, ... */
				entity_type?: string | null;
				/** @description match against the name, in any script */
				q?: string | null;
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_EntitySummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_poet_poets__site___slug__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				site: string;
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EntityDetail'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_poet_works_poets__site___slug__works_get: {
		parameters: {
			query?: {
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path: {
				site: string;
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_WorkSummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_entries_entries_get: {
		parameters: {
			query?: {
				/** @description rekhtadictionary, hindwi, rekhta or sufinama */
				site?: string | null;
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_EntrySummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	lookup_entry_entries_lookup_get: {
		parameters: {
			query: {
				/** @description a `code` from a work's word positions */
				code: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EntryGloss'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_entry_entries__site___slug__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				site: string;
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EntryDetail'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_tags_tags_get: {
		parameters: {
			query?: {
				/** @description restrict to one site */
				site?: string | null;
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_TagSummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_tag_works_tags__tag__works_get: {
		parameters: {
			query?: {
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path: {
				tag: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_WorkSummary_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_search_get: {
		parameters: {
			query: {
				/** @description words to search for, in any script */
				q: string;
				/** @description what to search */
				kind?: 'works' | 'entries' | 'poets';
				/** @description restrict to one site */
				site?: string | null;
				/** @description items per page */
				limit?: number;
				/** @description items to skip */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Page_SearchHit_'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	health_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Health'];
				};
			};
		};
	};
}
